<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- MACROS -->

    <xacro:include filename="material_macros.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/>

    <!-- BASE -->

    <!-- used for center of rotation of wheels -->
    <link name="base_link"></link>

    <!-- CHASSIS -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz='-0.1 0 0'/> <!-- chassis set just behind base_link-->
    </joint>

    <xacro:property name="body_x" value="0.3"/>
    <xacro:property name="body_y" value="0.3"/>
    <xacro:property name="body_z" value="0.15"/>
    <link name="chassis">
        <visual>
            <origin xyz="${body_x/2} 0 ${body_z/2}"/> <!-- place chassis at bottom back of visual-->
            <geometry>
                <box size="${body_x} ${body_y} ${body_z}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${body_x/2} 0 ${body_z/2}"/>
            <geometry>
                <box size="${body_x} ${body_y} ${body_z}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${body_x}" y="${body_y}" z="${body_z}">
            <origin xyz="${body_x/2} 0 ${body_z/2}" rpy="0 0 0"/> <!-- same as visual.origin-->
        </xacro:inertial_box>
    </link>

    <!-- WHEELS -->

    <xacro:property name="wheel_length" value="0.04"/>
    <xacro:property name="wheel_radius" value="0.05"/>

    <!-- LEFT WHEEL -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${body_y/2 + wheel_length/2} 0" rpy="-${pi/2} 0 0"/> <!-- by default ros cylinders are along vertical z point out, rotate sideways along -x-->
        <axis xyz="0 0 1"/> <!-- rotate forward around +z-->
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" radius="${wheel_radius}" length="${wheel_length}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- RIGHT WHEEL -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -${body_y/2 + wheel_length/2} 0" rpy="${pi/2} 0 0"/> <!-- by default ros cylinders are along vertical z point out, rotate sideways along +x-->
        <axis xyz="0 0 -1"/> <!-- rotate forward around +z-->
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" radius="${wheel_radius}" length="${wheel_length}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- CASTER WHEEL (frictionless hemisphere) -->

    <xacro:property name="caster_radius" value="${wheel_radius}"/>

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${body_x - caster_radius} 0 0"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="${caster_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

</robot>